name: CI

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://orga09cbdeb.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: .github/workflows
  
jobs:
  commit-from-power-apps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
         environment-url: ${{ env.POWER_APPS }}
         user-name: ${{ env.POWER_USER }}
         password-secret: ${{ env.POWER_PWD }}
         solution-name: ${{ env.SOLUTION_NAME }}
         solution-output-file: ${{ env.$EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
         
      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
         solution-file: ${{ env.$EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
         solution-folder: ${{ env.$EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}
         solution-type: 'unmanaged'
         overwrite-files: true
         
      - name: Synchronize Files
        run: |
          cmd /k ${{ env.$EXPORT_FOLDER }}/sync_repo_with_export.bat ./${{ env.SOLUTION_NAME }} ../../.
