name: CI

on:
  workflow_dispatch:

jobs:
  commit-from-power-apps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          cd .github/workflows
          dir
          cmd /k sync_repo_with_export.bat
          cmd /k newbat.bat
