name: Import_2 Power Apps

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  RUNNER_DEBUG: 1
  
jobs:
  import-to-power-apps:
    runs-on: windows-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"
          
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
    
      - id: import
        if: steps.checkout.outcome == 'success'
        name: Import Power Apps Solution
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
         environment-url: ${{ env.POWER_APPS }}
         user-name: ${{ env.POWER_USER }}
         password-secret: ${{ env.POWER_PWD }}
         solution-file: export\${{ env.SOLUTION_NAME }}.zip
         force-overwrite: true
         publish-changes: true 
        
