name: Export2Branch

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: export
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  commit-from-power-apps:
    runs-on: windows-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"
          
      - uses: actions/checkout@v4
    
      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
         environment-url: ${{ env.POWER_APPS }}
         user-name: ${{ env.POWER_USER }}
         password-secret: ${{ env.POWER_PWD }}
         solution-name: ${{ env.SOLUTION_NAME }}
         solution-output-file: ${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
         
      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
         solution-file: ${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
         solution-folder: ${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}
         solution-type: 'unmanaged'
         overwrite-files: true
         
      - name: Synchronize Files
        run: |
          cd ${{ env.EXPORT_FOLDER }}
          cmd /k sync_repo_with_export.bat ${{ GITHUB.WORKSPACE }}/${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }} ${{ GITHUB.WORKSPACE }}/${{ env.SOLUTION_NAME }}
          rm ${{ env.EXPORT_FOLDER }} -r -force

      - name: Commit changes
        run: |
          git add *
          git commit -m "Synchronized with ${{ env.POWER_USER }} from ${{ env.SOLUTION_NAME }} in Power Apps"
          git push

      - name: Create pull request
        run: |
         gh pr create `
         --title "${{ github.ref }} -> main" --body "Automated pull request creation from ${{ github.ref }} branch." `
         --reviewer ${{ github.actor }} --base "main" --head "${{ github.ref }}" --repo "${{ github.repository }}"
