name: Export2Branch

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: ${{ secrets.POWER_PWD }}
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: export
  WORKFLOW_FOLDER: .github/workflows
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  export-from-power-apps:
    runs-on: windows-latest
    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
        
      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: Export Power Apps Solution
        id: export
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
         environment-url: ${{ vars.POWER_APPS }}
         user-name: ${{ vars.POWER_USER }}
         password-secret: ${{ env.POWER_PWD }}
         solution-name: ${{ env.SOLUTION_NAME }}
         solution-output-file: ${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
         
      - name: Unpack Power Apps Solution
        id: unpack
        if: steps.export.outcome == 'success'
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
         solution-file: ${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
         solution-folder: ${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}
         solution-type: 'unmanaged'
         overwrite-files: true
         
      - name: Commit changes
        id: commit1
        if: steps.unpack.outcome == 'success'
        run: |
          git add *
          git commit -m "Synchronized with ${{ env.POWER_USER }} from ${{ env.SOLUTION_NAME }} in Power Apps"
          git push
          
  sync-solution-repo:
    needs: export-from-power-apps
    runs-on: windows-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
          
      - name: Synchronize Files
        id: sync
        if: steps.checkout.outcome == 'success'
        run: |
          cd ${{ env.WORKFLOW_FOLDER }}
          cmd /k sync_repo_with_export.bat `
          ${{ GITHUB.WORKSPACE }}/${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }} `
          ${{ GITHUB.WORKSPACE }}/${{ env.SOLUTION_NAME }}

      - name: Remove Export Files
        id: remove
        if: steps.sync.outcome == 'success'
        run: rm ${{ env.EXPORT_FOLDER }} -r -force
        
      - name: Commit changes
        id: commit
        if: steps.remove.outcome == 'success'
        run: |
          git add *
          git commit -m "Synchronized with ${{ env.POWER_USER }} from ${{ env.SOLUTION_NAME }} in Power Apps"
          git push
          
  create-pull-request:
    needs: [sync-solution-repo, export-from-power-apps]
    runs-on: windows-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: Create pull request
        id: pullrequest
        if: steps.checkout.outcome == 'success'
        run: |
         gh pr create `
         --title "${{ github.ref }} -> main" --body "Automated pull request creation from ${{ github.ref }} branch." `
         --reviewer ${{ github.actor }} --base "main" --head "${{ github.ref }}" --repo "${{ github.repository }}"
