name: Export_2 Synchronize with Exported Solution

on:
  workflow_dispatch:
  
env:
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: export
  WORKFLOW_FOLDER: .github/workflows
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  commit-from-power-apps:
    runs-on: windows-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"  
          
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v2
        
      - id: sync
        if: steps.checkout.outcome == 'success'
        name: Synchronize Files
        run: |
          cd ${{ env.WORKFLOW_FOLDER }}
          cmd /k sync_repo_with_export.bat ${{ GITHUB.WORKSPACE }}\${{ env.EXPORT_FOLDER }}\${{ env.SOLUTION_NAME }} ${{ GITHUB.WORKSPACE }}\${{ env.SOLUTION_NAME }}
          # rm ../../${{ env.EXPORT_FOLDER }} -r -force

      - id: remove
        if: steps.sync.outcome == 'success'
        name: Remove Export Files
        run: rm ${{ env.EXPORT_FOLDER }} -r -force
        
      - id: commit
        if: steps.remove.outcome == 'success'
        name: Commit changes
        run: |
          git add *
          git commit -m "Synchronized with ${{ env.POWER_USER }} from ${{ env.SOLUTION_NAME }} in Power Apps"
          git push
          
      - id: pullrequest
        if: steps.commit.outcome == 'success'
        name: Create pull request
        run: |
         gh pr create `
         --title "${{ github.ref }} -> main" --body "Automated pull request creation from ${{ github.ref }} branch." `
         --reviewer ${{ github.actor }} --base "main" --head "${{ github.ref }}" --repo "${{ github.repository }}"




