name: Export_1 Export solution and commit

on:
  workflow_dispatch:
  
env:
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: export
  WORKFLOW_FOLDER: .github/workflows
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  export-from-power-apps:
    runs-on: windows-latest
    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
        
      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"
          
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
    
      - id: export
        if: steps.checkout.outcome == 'success'
        name: Export Power Apps Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
         environment-url: ${{ vars.POWER_APPS }}
         user-name: ${{ vars.POWER_USER }}
         password-secret: ${{ secrets.POWER_PWD }}
         solution-name: ${{ env.SOLUTION_NAME }}
         solution-output-file: ${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
         
      - id: unpack
        if: steps.export.outcome == 'success'
        name: Unpack Power Apps Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
         solution-file: ${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
         solution-folder: ${{ env.EXPORT_FOLDER }}/${{ env.SOLUTION_NAME }}
         solution-type: 'unmanaged'
         overwrite-files: true
         process-canvas-apps: true
         
      - id: commit
        if: steps.unpack.outcome == 'success'
        name: Commit changes
        run: |
          git add *
          git commit -m "Exported solution ${{ env.SOLUTION_NAME }} in Power Apps by ${{ env.POWER_USER }}"
          git push

