name: Import_1 Zip Directory and Import to Power Apps

on:
  workflow_dispatch:
  
env:
  SOLUTION_NAME: CO2Sol
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  import-to-power-apps:
    runs-on: windows-latest
    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
        
      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"
          
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: canvas
        if: steps.checkout.outcome == 'success'
        name: Pack the canvas app to msapp
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          pac canvas pack --sources export\${{ env.SOLUTION_NAME }}\CanvasApps\src\new_co2canvas_0005b --msapp new_co2canvas_0005b_DocumentUri.msapp
          
      - id: pack
        if: steps.canvas.outcome == 'success'
        name: Pack Power Apps Solution
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
         solution-file: ${{ env.SOLUTION_NAME }}.zip
         solution-folder: export\${{ env.SOLUTION_NAME }}
         solution-type: 'unmanaged'
         overwrite-files: true

      - id: import
        if: steps.pack.outcome == 'success'
        name: Import Power Apps Solution
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
         environment-url: ${{ vars.POWER_APPS }}
         user-name: ${{ vars.POWER_USER }}
         password-secret: ${{ secrets.POWER_PWD }}
         solution-file: ${{ env.SOLUTION_NAME }}.zip
         force-overwrite: true
         publish-changes: true
         process-canvas-apps: true

        
