name: Template call

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: stepg0/goodaiteam/.github/workflows/template_commit.yml@main
    with:
      solution_name: Technical
      power_env: ${{ vars.POWER_APPS }}
      power_user: ${{ vars.POWER_USER }}
      gh_email: step-go@hotmail.com
    secrets: 
      gh_token: ${{ secrets.GH_TOKEN }}
      power_pwd: ${{ secrets.POWER_PWD }}
      

