name: TEST_SIMPLE

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: .github/workflows
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  commit-from-power-apps:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"

      - name: Create pull request
        run: |
         gh pr create `
         --title "${{ github.ref }} -> main" --body "Automated pull request creation from ${{ github.ref }} branch." `
         --reviewer ${{ github.actor }} --base "main" --head "${{ github.ref }}" --repo "${{ github.repository }}"






