name: Test

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: export
  WORKFLOW_FOLDER: .github/workflows
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cmd /k sync_repo_with_export.bat `
          ${{ GITHUB.WORKSPACE }}/a `
          ${{ GITHUB.WORKSPACE }}/b

