name: Test

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: export
  WORKFLOW_FOLDER: .github/workflows
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/powerplatform-actions/actions-install@v1
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        working-directory: ${{ env.WORKFLOW_FOLDER }}
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          pac canvas pack --sources MyHelloWorldFiles --msapp HelloWorld.msapp

