name: TEST_SIMPLE

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: .github/workflows
  
jobs:
  commit-from-power-apps:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create file
        run: echo "Hello, World!" > my_file.txt

      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"
          
      - name: Commit changes
        run: |
          git add my_file.txt
          git commit -m "Add my_file.txt"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}






