name: Test

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: CO2Sol
  EXPORT_FOLDER: export
  WORKFLOW_FOLDER: .github/workflows
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/powerplatform-actions/actions-install@v1
      # Runs a set of commands using the runners shell

      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: canvas
        if: steps.checkout.outcome == 'success'
        name: Pack the canvas app to msapp
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          pac canvas pack --sources export\${{ env.SOLUTION_NAME }}\CanvasApps\src\new_co2canvas_0005b --msapp export\${{ env.SOLUTION_NAME }}\CanvasApps\new_co2canvas_0005b_DocumentUri.msapp


      - id: commit
        if: steps.remove1.outcome == 'success'
        name: Commit changes
        run: |
          git add *
          git commit -m "Exported solution ${{ env.SOLUTION_NAME }} in Power Apps by ${{ env.POWER_USER }}"
          git push
          
