name: TEST_SIMPLE

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: .github/workflows
  
jobs:
  commit-from-power-apps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Commit changes
        run: |
          git add my_file.txt
          git commit -m "Add my_file.txt"
          git push






