name: TEST_SIMPLE

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: .github/workflows
  
jobs:
  commit-from-power-apps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Synchronize Files
        run: |
          git fetch origin ${{ env.POWER_USER }}
          if ( $? -ne 0 ); then
            echo "Branch user1 does not exist. Creating from main branch..."
            git checkout main
            git checkout -b ${{ env.POWER_USER }}
            git push origin ${{ env.POWER_USER }}
          else
            echo "Branch ${{ env.POWER_USER }} already exists."
          fi


