name: TEST_SIMPLE

on:
  workflow_dispatch:
  
env:
  POWER_APPS: 'https://skillboosterccapart13senvironmen.crm16.dynamics.com'
  POWER_USER: 'SkillboosterCCAPart13@mscloudguild.onmicrosoft.com' #EACH USER
  POWER_PWD: 'Fuy71602' #EACH USER
  SOLUTION_NAME: Technical
  EXPORT_FOLDER: .github/workflows
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  commit-from-power-apps:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create file
        run: echo "Hello, World!" > my_file.txt

      - name: Configure Git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "step-go@hotmail.com"
          echo ${{ secrets.GH_TOKEN }}
          
      - name: Commit changes
        run: |
          git add my_file.txt
          git commit -m "Add my_file.txt"
          git push

      - name: Create pull request
        run: |
         # Use the GitHub CLI to create a pull request
         gh pr create \
           # Set the title of the pull request
           --title "${{ github.ref }} -> main" \
           # Set the commit message for the pull request
           --body "Automated pull request creation from ${{ github.ref }} branch." \
           # Specify the github reviewer user id for the pull request --reviewer "reviewer user id" \
           # Specify the base branch name for the pull request
           --base "main" \
           # Specify the head branch for the pull request
           --head "${{ github.ref }}" \
           # Specify the repository where the pull request will be created
           --repo "${{ github.repository }}"

        






